# This file is a template, and might need editing before it works on your project.
# Official docker image.

services:
  - docker:dind

build-master:
  image: docker:latest
  stage: build
  script:
    - docker run hello-world
  only:
    - master
