stages:
  - build
  - test

job A:
  stage: build
  script:
    - ls
    - ls public/
  cache:
    key: same-key
    paths:
      - public/

job B:
  stage: test
  script: make test
    - ls
    - ls public/
    - ls vendor/
  cache:
    key: same-key
    paths:
      - vendor/
