image: bohushvitali/frontend-ci

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://localhost:2375
  WEB_APPLICATION_STAGING_URL: https://sandbox-50983.firebaseapp.com/

stages:
  - audit

web-application-lighthouse:
  stage: audit
  script:
    - mkdir -p sources/applications/reports/lighthouse
    - CHROME_PATH=/usr/bin/chromium-browser lighthouse --chrome-flags="--headless" https://github.com
    - echo Web Application lighthouse analysis finished
  artifacts:
    paths:
      - sources/applications/reports
