image: bohushvitali/frontend-ci

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://localhost:2375
  WEB_APPLIATOIN_STAGING_URL: https://sandbox-bcdc7.firebaseapp.com/

services:
  - docker:dind

stages:
  - build
  - test
  - staging
  - analyze
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .pnpm-store/

before_script:
  - npm config set store .pnpm-store
  - npm set verify-store-integrity false

frontend-web-application-build:
  stage: build
  environment:
    name: staging
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    policy: push
    paths:
      - .pnpm-store/
  script:
    - pnpm install --prefix sources/frontend
    - build.web.application
    - echo "Build Finished"
  artifacts:
    paths:
      - sources/frontend/dist

check-formatting:
  stage: test
  environment:
    name: staging
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    policy: push
    paths:
      - .pnpm-store/
  script:
    - npm --prefix sources/frontend run format.check $(git rev-parse $CI_COMMIT_SHA) $CI_COMMIT_SHA
    - echo "Format Check Finished"

check-linting:
  stage: test
  environment:
    name: staging
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    policy: push
    paths:
      - .pnpm-store/
  script:
    - npm --prefix sources/frontend run lint.check
    - echo "Linting Check Finished"

frontend-web-application-unit-tests:
  stage: test
  environment:
    name: staging
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    policy: pull
    paths:
      - .pnpm-store/
  script:
    - pnpm install --prefix sources/frontend --shamefully-flatten
    - npm --prefix sources/application run test.jest.coverage
    - echo "Web Application Unit Tests Finished"
  artifacts:
    paths:
      - sources/frontend/dist
      - sources/frontend/reports

frontend-web-application-e2e-tests:
  stage: test
  environment:
    name: staging
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    policy: pull
    paths:
      - .pnpm-store/
  script:
    - pnpm install --prefix sources/frontend --shamefully-flatten
    - npm --prefix sources/frontend run e2e.web.application.report
    - echo "Web Application E2E Tests Finished"
  artifacts:
    paths:
      - sources/frontend/dist
      - sources/frontend/reports

# buildsize:
#   stage: test
#   script:
#     - echo 1

# depgraph:
#   stage: test
#   script:
#     - echo 1

publish-hiptest:
  before_script:
    - echo Skip
  image: docker:stable
  stage: build
  script:
    - docker run hello-world
  only:
    - master
