image: bohushvitali/frontend-ci

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://localhost:2375
  WEB_APPLIATOIN_STAGING_URL: https://sandbox-bcdc7.firebaseapp.com/

services:
  - docker:dind

stages:
  - prepare
  - build
  - test
  - staging
  - audit
  - reports
  - production

cache:
  key: $CI_PROJECT_NAMESPACE
  paths:
    - .pnpm-store/

before_script:
  - npm config set store .pnpm-store
  - npm config set verify-store-integrity false
  - npm config set rebuild-bundle false

frontend-dependencies-install:
  stage: prepare
  before_script:
    - npm config set store .pnpm-store
  cache:
    key: $CI_PROJECT_NAMESPACE
    paths:
      - .pnpm-store/
  script:
    - pnpm install --prefix sources/frontend
    - pnpm install --prefix sources/frontend/functions
    - echo "Dependencies Install Finished"
  only:
    - master
  when: always
  allow_failure: false

frontend-web-application-build-staging:
  stage: build
  environment:
    name: staging
  dependencies:
    - frontend-dependencies-install
  cache:
    key: $CI_PROJECT_NAMESPACE
    policy: pull
    paths:
      - .pnpm-store/
  script:
    - pnpm install --prefix sources/frontend --offline
    - npm run --prefix sources/frontend udk.web.application.build
    - echo "Stating Build Finished"
  artifacts:
    paths:
      - sources/frontend/dist
  only:
    - master
  when: always
  allow_failure: false

frontend-web-application-build-production:
  stage: build
  environment:
    name: production
  dependencies:
    - frontend-dependencies-install
  cache:
    key: $CI_PROJECT_NAMESPACE
    policy: pull
    paths:
      - .pnpm-store/
  script:
    - pnpm install --prefix sources/frontend --offline
    - npm run --prefix sources/frontend udk.web.application.build
    - mkdir sources/frontend/production
    - cp -r sources/frontend/dist/apps/* sources/frontend/production
    - echo "Production Build Finished"
  artifacts:
    paths:
      - sources/frontend/dist
      - sources/frontend/production
  only:
    - master
  when: always
  allow_failure: false

frontend-check-formatting:
  stage: test
  dependencies:
    - frontend-dependencies-install
  cache:
    key: $CI_PROJECT_NAMESPACE
    policy: pull
    paths:
      - .pnpm-store/
  script:
    - pnpm install --prefix sources/frontend --offline
    - npm run --prefix sources/frontend format.check $(git rev-parse $CI_COMMIT_SHA) $CI_COMMIT_SHA
    - echo "Frontend Check Formatting Finished"

frontend-check-linting:
  stage: test
  dependencies:
    - frontend-dependencies-install
  cache:
    key: $CI_PROJECT_NAMESPACE
    policy: pull
    paths:
      - .pnpm-store/
  script:
    - pnpm install --prefix sources/frontend --offline
    - npm run --prefix sources/frontend lint.check
    - echo "Frontend Check Linting Finished"

frontend-unit-tests:
  stage: test
  dependencies:
    - frontend-dependencies-install
  cache:
    key: $CI_PROJECT_NAMESPACE
    policy: pull
    paths:
      - .pnpm-store/
  script:
    - pnpm install --prefix sources/frontend --offline
    - npm run --prefix sources/frontend test.jest.coverage
    - echo "Web Application Unit Tests Finished"
  artifacts:
    paths:
      - sources/frontend/reports

frontend-compodoc:
  stage: test
  dependencies:
    - frontend-dependencies-install
  cache:
    key: $CI_PROJECT_NAMESPACE
    policy: pull
    paths:
      - .pnpm-store/
  script:
    - pnpm install --prefix sources/frontend --offline
    - npm run --prefix sources/frontend docs.compodoc
    - echo "Web Application Compodoc Generation Finished"
  artifacts:
    paths:
      - sources/frontend/reports

frontend-storybook:
  stage: test
  dependencies:
    - frontend-dependencies-install
  cache:
    key: $CI_PROJECT_NAMESPACE
    policy: pull
    paths:
      - .pnpm-store/
  script:
    - pnpm install --prefix sources/frontend --offline
    - npm run --prefix sources/frontend storybook.build
    - echo "Storybook Building Finished"
  artifacts:
    paths:
      - sources/frontend/reports

frontend-dependencies-graph:
  stage: test
  dependencies:
    - frontend-dependencies-install
  cache:
    key: $CI_PROJECT_NAMESPACE
    policy: pull
    paths:
      - .pnpm-store/
  script:
    - pnpm install --prefix sources/frontend --offline
    - npm run --prefix sources/frontend dep-graph
    - echo "Frontend Dependencies Graph Generation Finished"
  artifacts:
    paths:
      - sources/frontend/reports

frontend-web-application-bundle-analysis:
  stage: test
  dependencies:
    - frontend-dependencies-install
  cache:
    key: $CI_PROJECT_NAMESPACE
    policy: pull
    paths:
      - .pnpm-store/
  script:
    - pnpm install --prefix sources/frontend --offline
    - npm run --prefix sources/frontend analyze.web.application.bundle
    - echo "Web Application Bundle Analysis Finished"
  artifacts:
    paths:
      - sources/frontend/reports

frontend-web-application-e2e-tests:
  stage: test
  dependencies:
    - frontend-dependencies-install
  cache:
    key: $CI_PROJECT_NAMESPACE
    policy: pull
    paths:
      - .pnpm-store/
  script:
    - pnpm install --prefix sources/frontend --offline
    - npm run --prefix sources/frontend e2e.web.application
    - echo "Web Application E2E Tests Finished"
  artifacts:
    paths:
      - sources/frontend/reports

frontend-application-web-lighthouse:
  stage: audit
  dependencies:
    - frontend-application-web-deploy-staging
  script:
    - mkdir -p sources/frontend/reports/lighthouse
    - lighthouse-ci $WEB_APPLIATOIN_STAGING_URL --silent --report sources/frontend/reports/lighthouse
    - echo "Web Application Lighthouse Analysis Finished"
  artifacts:
    paths:
      - sources/frontend/reports

frontend-application-web-artillery:
  stage: audit
  dependencies:
    - frontend-application-web-deploy-staging
  script:
    - mkdir -p sources/frontend/reports/lighthouse
    - artillery quick --count 10 -n 20 https://artillery.io/
    - echo "Web Application Artillery Load Tests Finished"
  artifacts:
    paths:
      - sources/frontend/reports

frontend-application-web-deploy-staging:
  stage: staging
  dependencies:
    - frontend-dependencies-install
    - frontend-web-application-build-staging
  environment:
    name: staging
  cache:
    key: $CI_PROJECT_NAMESPACE
    policy: pull
    paths:
      - .pnpm-store/
  script:
    - pnpm install --prefix sources/frontend --offline
    - pnpm install --prefix sources/frontend/functions --offline
    - npm run --prefix sources/frontend deploy.web.application
    - echo "Staging Deployment Finished"
  artifacts:
    paths:
      - sources/frontend/dist
  when: always

frontend-application-web-deploy-production:
  stage: production
  dependencies:
    - frontend-dependencies-install
    - frontend-web-application-build-production
  environment:
    name: production
  cache:
    key: $CI_PROJECT_NAMESPACE
    policy: pull
    paths:
      - .pnpm-store/
  script:
    - pnpm install --prefix sources/frontend --offline
    - pnpm install --prefix sources/frontend/functions --offline
    - mkdir sources/frontend/dist/apps
    - mv sources/frontend/production/* sources/frontend/dist/apps
    - npm run --prefix sources/frontend deploy.web.application
    - echo "Production Deployment Finished"
  artifacts:
    paths:
      - sources/frontend/production
  only:
    - master
  when: manual

pages:
  stage: reports
  before_script:
    - echo Skip Before Scripts
  dependencies:
    - frontend-unit-tests
    - frontend-compodoc
    - frontend-storybook
    - frontend-dependencies-graph
    - frontend-web-application-bundle-analysis
    - frontend-web-application-e2e-tests
    - frontend-application-web-lighthouse
  script:
    - mkdir public
    - cp -r sources/frontend/tools/report-wrapper/* public
    - cp -r sources/frontend/reports/* public
    - echo "Pages Publishing Finished"
  artifacts:
    paths:
      - public
      - sources/frontend/reports
    expire_in: 30 days

hiptest:
  stage: reports
  image: docker:stable
  before_script:
    - echo Skip Before Scripts
  cache: {}
  script:
    - docker run -it --rm -u $UID -v $(pwd):/app hiptest/hiptest-publisher --config-file=sources/frontend/hiptest-publisher.conf --push="sources/frontend/reports/apps/web-application/mocha/*.xml"
    - echo "Hiptest Report Pablishing Finished"
  artifacts:
    paths:
      - sources/frontend/reports
