image: bohushvitali/frontend-ci

variables:
  WEB_APPLIATOIN_STAGING_URL: https://sandbox-bcdc7.firebaseapp.com/
stages:
  - build
  - test
  - staging
  - analyze
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - sources/frontend/node_modules/
    - sources/frontend/functions/node_modules/

before_script:
  - echo "Before script section"
  - npm --prefix sources/frontend ci
  - npm --prefix sources/frontend/functions ci

after_script:
  - echo "After script section"
  - echo "For example you might do some cleanup here"

build1:
  stage: build
  script:
    - echo "Do your build here"

frontend-web-application-build:
  stage: build
  environment:
    name: staging
  script:
    - npm --prefix sources/frontend run build.web.application
  artifacts:
    paths:
      - sources/frontend/dist

check-formatting:
  stage: test
  dependencies:
    - frontend-web-application-build
  script:
    - npm --prefix sources/frontend run format.check $(git rev-parse $CI_COMMIT_SHA) $CI_COMMIT_SHA

check-linting:
  stage: test
  dependencies:
    - frontend-web-application-build
  script:
    - npm --prefix sources/frontend run affected.lint $(git rev-parse $CI_COMMIT_SHA) $CI_COMMIT_SHA

test-application:
  stage: test
  environment:
    name: staging
  dependencies:
    - build-application
  script:
    - npm --prefix sources/application run test.jest.coverage
  artifacts:
    paths:
      - sources/frontend/reports

frontend-web-application-e2e:
  stage: test
  environment:
    name: staging
  dependencies:
    - frontend-web-application-build
  script:
    - npm --prefix sources/frontend run e2e.web.application.report
  artifacts:
    paths:
      - sources/frontend/reports

buildsize:
  stage: test
  script:
    - echo 1

depgraph:
  stage: test
  script:
    - echo 1

deploy1:
  stage: deploy
  script:
    - echo "Do your deploy here"
