image: averagemarcus/lighthouse

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://localhost:2375
  WEB_APPLICATION_STAGING_URL: https://sandbox-50983.firebaseapp.com/

stages:
  - audit

web-application-lighthouse:
  stage: audit
  script:
    - mkdir -p sources/applications/reports/lighthouse
    - lighthouse https://sandbox-50983.firebaseapp.com/ --quiet --chrome-flags="--headless"
    - echo Web Application lighthouse analysis finished
  artifacts:
    paths:
      - sources/applications/reports
