stages:
  - build
  - test

before_script:
  - echo "Hello"

cache:
  key: build-cache
  paths:
    - vendor/

job A:
  stage: build
  script:
    - mkdir vendor/
    - echo "build" > vendor/hello.txt

job B:
  stage: test
  script:
    - cat vendor/hello.txt
