stages:
  - build
  - test

job A:
  stage: build
  script:
    - ls
    - mkdir public
    - touch public/file.txt
    - ls public/
  cache:
    key: same-key
    paths:
      - public/

job B:
  stage: test
  script:
    - ls
    - ls public/
    - ls vendor/
  cache:
    key: same-key
    paths:
      - public/
      - vendor/
