image: bohushvitali/frontend-ci

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://localhost:2375
  WEB_APPLICATION_STAGING_URL: https://sandbox-50983.firebaseapp.com/

web-application-lighthouse:
  stage: audit
  dependencies:
    - web-application-deploy-staging
  script:
    - mkdir -p sources/applications/reports/lighthouse
    - lighthouse-ci -s $WEB_APPLICATION_STAGING_URL
    - echo Web Application lighthouse analysis finished
  artifacts:
    paths:
      - sources/applications/reports
