image: bohushvitali/frontend-ci

stages:
  - build
  - test
  - staging
  - analyze
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - sources/frontend/node_modules/
    - sources/frontend/functions/node_modules/

before_script:
  - echo "Before script section"
  - npm --prefix sources/frontend ci
  - npm --prefix sources/frontend/functions ci

after_script:
  - echo "After script section"
  - echo "For example you might do some cleanup here"

build1:
  stage: build
  script:
    - echo "Do your build here"

frontend-web-application-build:
  stage: build
  environment:
    name: staging
  script:
    - npm --prefix sources/frontend run build.web.application
  artifacts:
    paths:
      - sources/frontend/dist

test1:
  stage: test
  script:
    - echo "Do a test here"
    - echo "For example run a test suite"

frontend-web-application-e2e:
  stage: test
  environment:
    name: staging
  dependencies:
    - frontend-web-application-build
  script:
    - npm --prefix sources/frontend run e2e.web.application.report
  artifacts:
    paths:
      - sources/frontend/dist/reports/web-application/codecept

check-formatting:
  stage: test
  dependencies:
    - frontend-web-application-build
  script:
    - npm --prefix sources/frontend run format:check $(git rev-parse $CI_COMMIT_SHA^5) $CI_COMMIT_SHA

buildsize:
  stage: test
  script:
    - echo 1

depgraph:
  stage: test
  script:
    - echo 1

deploy1:
  stage: deploy
  script:
    - echo "Do your deploy here"
