apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
    - image: gcr.io/sandbox-228621/example-go-web
      context: ./sources/services/example-go-app/
    - image: gcr.io/sandbox-228621/example-go-app
      context: ./sources/services/example-go-app/
    - image: gcr.io/sandbox-228621/example-python
      context: ./sources/services/example-python/
    - image: gcr.io/sandbox-228621/example-node
      context: ./sources/services/example-node/
      sync:
        "*.js": .
deploy:
  kubectl:
    manifests:
      - ./sources/services/example-go-web/k8s/*
      - ./sources/services/example-go-app/k8s/*
      - ./sources/services/example-node/k8s/*
      - ./sources/services/example-python/k8s/*
