export const environment = {
  production: false,
  apiUrl: "http://127.0.0.1:4000",
  staticContentServerUrl: "",
  firebase: {
    apiKey: "AIzaSyCPgEpt_kt0KjzYJ3_moCgqYwZHNB-WEY8",
    authDomain: "sandbox-50983.firebaseapp.com",
    databaseURL: "https://sandbox-50983.firebaseio.com",
    projectId: "sandbox-50983",
    storageBucket: "sandbox-50983.appspot.com",
    messagingSenderId: "1019120661490"
  },
  googleAnalytics: true,
  gaTrackingCode: "",
  googeMapsApiKey: "",
  baseRoutePath: "",
  demoAnimationsPath: "demo-animations",
  demoAssemblyscriptPath: "demo-assemblyscript",
  demoBabylonPath: "demo-babylon",
  demoBmToolsPath: "demo-bm-tools",
  demoCovalentUiPath: "demo-covalent-ui",
  demoCssLayoutsPath: "demo-css-layouts",
  demoForceGraphPath: "demo-force-graph",
  demoGoogleMapsPath: "demo-google-maps",
  demoHeroesPath: "demo-heroes",
  demoImagePreviewPath: "demo-image-preview",
  demoKnowledgeBasePath: "demo-knowledge-base",
  demoMaterialPath: "demo-material",
  demoOpencvPath: "demo-opencv",
  demoReglPath: "demo-regl",
  demoTensorflowPath: "demo-tensorflow",
  demoUniversalPath: "demo-universal",
  demoVersionPath: "demo-version",
  demoWebassemblyPath: "demo-webassembly",
  uiAuthFirebasePath: "ui-auth-firebase",
  demoItemsPath: "demo-items",
  viewWelcomePath: "view-welcome"
};
