FROM node:alpine as build-env
RUN apk add --no-cache curl
RUN curl -L https://unpkg.com/@pnpm/self-installer | node
WORKDIR /app
COPY . /app
RUN pnpm install
RUN npm run build.web.application

FROM nginx:latest

COPY --from=build-env /app/docker/configs/nginx.conf /etc/nginx/nginx.conf
COPY --from=build-env /app/docker/configs/mime.types /etc/nginx/mime.types
COPY --from=build-env /app/docker/configs/default.conf /etc/nginx/conf.d/default.conf
RUN mkdir -p /srv/www
COPY /app/dist/apps/web-application/browser /srv/www
EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]
