FROM node:alpine as build-env

RUN apk add --update --no-cache git tar curl vim python python-dev make gcc g++ automake autoconf linux-headers libgcc libstdc++

RUN npm install --global node-sass @angular/cli

RUN mkdir -p /opt/build
WORKDIR /opt/build

COPY package.json .

COPY . .

RUN npm install

RUN npm run build

FROM node:alpine

WORKDIR /opt/app

COPY --from=build-env /opt/build/dist /opt/app/dist

CMD [ "node", "/opt/app/dist/apps/api/main" ]
