FROM node:10-alpine as build-env

COPY . /app
WORKDIR /app
RUN npm install
RUN npm run web-application.build

FROM nginx:alpine
COPY --from=build-env /app/dist/apps/web-application/browser /app
COPY --from=build-env /app/nginx.conf /etc/nginx/nginx.conf
COPY --from=build-env /app/mime.types /etc/nginx/mime.types
COPY --from=build-env /app/gzip.conf /etc/nginx/gzip.conf

EXPOSE 9000/tcp
