FROM node:alpine as build-env
RUN apk add --no-cache curl
RUN curl -L https://unpkg.com/@pnpm/self-installer | node
WORKDIR /app
COPY . /app
RUN pnpm install
RUN npm run build.web.application

FROM nginx:alpine
COPY --from=build-env /app/dist/apps/web-application/browser /app
COPY --from=build-env /app/nginx.conf /etc/nginx/nginx.conf
COPY --from=build-env /app/mime.types /etc/nginx/mime.types
COPY --from=build-env /app/gzip.conf /etc/nginx/gzip.conf
EXPOSE 9000/tcp
