apiVersion: v1
kind: Service
metadata:
  name: example-go-app
  labels:
    app: example-go-app
spec:
  clusterIP: None
  ports:
    - port: 50051
      name: example-go-app
  selector:
    app: example-go-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-go-app
  labels:
    app: example-go-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-go-app
  template:
    metadata:
      labels:
        app: example-go-app
    spec:
      containers:
        - name: example-go-app
          image: gcr.io/sandbox-228621/example-go-app
          ports:
            - containerPort: 50051
